export const USER_REGISTRATION = 'USER_REGISTRATION'
export const USER_REGISTRATION_SUCCESS = 'USER_REGISTRATION_SUCCESS'
export const USER_REGISTRATION_FAIL = 'USER_REGISTRATION_FAIL'

export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

// HAWALA LIST
export const HAWALA_LIST = 'HAWALA_LIST'
export const GET_HAWALA_LIST_SUCCESS = 'GET_HAWALA_LIST_SUCCESS'
export const GET_HAWALA_LIST_FAIL = 'GET_HAWALA_LIST_FAIL'

//GET Transaction List

export const CLIENT_LIST = 'CLIENT_LIST'
export const GET_CLIENT_LIST_SUCCESS = 'GET_CLIENT_LIST_SUCCESS'
export const GET_CLIENT_LIST_FAIL = 'GET_CLIENT_LIST_FAIL'